$global:All = @(
    "pip-services3-commons-node"
    "pip-services3-components-node"
    "pip-services3-container-node"
    "pip-services3-test-node"
    "pip-services3-data-node"
    "pip-services3-rpc-node"
    "pip-services3-messaging-node"
    "pip-services3-facade-node"
    "pip-services3-elasticsearch-node"
    "pip-services3-memcached-node"
    "pip-services3-redis-node"
    "pip-services3-fluentd-node"
    "pip-services3-mongodb-node"
    "pip-services3-prometheus-node"
    "pip-services3-seneca-node"
    "pip-services3-mqtt-node"
    "pip-services3-aws-node"
)

$global:Frameworks = @(
    "pip-services3-commons-node"
    "pip-services3-components-node"
    "pip-services3-test-node"
    "pip-services3-container-node"
    "pip-services3-data-node"
    "pip-services3-rpc-node"
    "pip-services3-messaging-node"
    "pip-services3-facade-node"
)
